domain: cli
language: Python
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: SEIR
project_slug: SEIR
project_short_description: SEIR modelling of covid19
version: 0.1.0
license: MIT
command_line_interface: Click
use_pytest: y
template_version: '0.1.0 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
