version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "development"
    #default_labels:
    #    - "dependabot" # TODO COOKIETEMPLE: You may add a dependabot label to all pull requests. Note that you must create this label on Github first.
    commit_message:
        prefix: "[DEPENDABOT]"
